class EnguinsDropdown {
  List<String> anguinDropdown = [
    "Ambulance",
    "Art car",
    "Auto-tamponneuse",
    "Automobile de collection",
    "Baboulin",
    "Beutepanzer",
    "Buggy",
    "Cab forward",
    "Camionnette",
    "Camping-car",
    "Coupé 2+2 (automobile)",
    "Cyclecar",
    "Dépanneuse",
    "Empennage de voiture",
    "Gyrocar",
    "Jeepney",
    "Mulet (automobile)",
    "Muscle car",
    "Pony car",
    "Runabout (automobile)",
    "Sandrail",
    "Semi-chenillé",
    "Siège de coffre",
    "Sonderkraftfahrzeug",
    "Swamp buggy",
    "Tricar",
    "Véhicule",
    "Véhicule d'occasion",
    "Véhicule de liaison",
    "Voiture à moteur de moto",
    "Voiture sans permis",
    "Voiture solaire",
    "Voiturette de golf",
    "Chargeuse compacte",
    "Mini Pelle",
    "Chargeuses pneus",
    "Chargeuses pelleteuse",
    "Finisseur",
    "machine à coffrage glissant", 
    "répandeur de chaux", 
    "gravillonneur auto-moteur", 
    "pulvimixeur", 
    "fraiseuse",
    "Niveleuse ",
    "Compacteur",
    "Rouleaux duplex",
    "Rouleaux monobille",
    "DUMPER",
    "TOMBEREAUX",
    "Décapeuse automotrice"
  ];
}
